apiVersion: v1
kind: Service
metadata:
  name: apuestas-service
  labels:
    app: apuestas-service
spec:
  type: ClusterIP
  selector:
    app: apuestas-service
  ports:
    - name: http
      port: 8005
      targetPort: 8005
      protocol: TCP
