apiVersion: v1
kind: Secret
metadata:
  name: casino-secrets
type: Opaque
stringData:
  JWT_SECRET: "cambiame-en-produccion"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "casino"
  DB_PASSWORD: "casino"
  DB_NAME: "casino_db"